### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by RickCogley** [jaydenseric/Barebones#12]
Hi Jayden - just wanted to say thank you for your help. I launched my site refresh today. 

http://rick.cogley.info/colophon/

I linked you in the colophon, but please let me know if you'd rather I link a different url from this repo. I'm happy to do so. 

Kind regards,
Rick

**Comment by jaydenseric** [comment]
Fantastic! Glad it all came together, and thanks for the shoutout :)
