### ISSUE TITLE
package.json upgrade

### ISSUE THREAD

**Issue by RickCogley** [jaydenseric/Barebones#13]
HI @jaydenseric, I noticed you upgraded some components in package.json. 

To do the upgrade, could you please confirm: do I update the version numbers like you have in package.json, then simply run npm install?

**Comment by jaydenseric** [comment]
Yep, although I like to delete `node_modules` before running `npm install` just to be sure.

A handy tool to install globaly is [npm-check-updates](https://github.com/tjunnone/npm-check-updates) or alternativly [npm-check](https://github.com/dylang/npm-check), if you would like to keep an eye on dependacy updates yourself.
