### ISSUE TITLE
support for more font format

### ISSUE THREAD

**Issue by easonzhuyi** [jaydenseric/Barebones#6]
The template just generate only woff base64 code in scss file. How to define the template that make it support for more font format and generate svg ttf eot base64 in scss file? Thanks

**Comment by jaydenseric** [comment]
This is deliberate, WOFF is the only format you need to use these days. [Can I Use](http://caniuse.com/#feat=woff) will show Opera Mini to be a problem at 5.35% global market share, but [it really isn't a concern](http://raddevon.com/articles/where-are-opera-mini-users) unless you are marketing to the poorest parts of Africa. In Australia the market share is 0.09%. Barebones is IE9+, if you have to support IE8 then you will need to handle the fonts manually.

WOFF 2.0 is really nice but [poorly supported](http://caniuse.com/#search=woff2). As you would still need to include the older format, Base64 embedding both would not be a good idea. [HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) is upon us, and it handles seperate requests realy well. I am considering dropping the special workflow for Base64 embedding in favour of simple `@font-face` declarations referencing separately cachable WOFF 2.0 and fallback WOFF assets.
