### ISSUE TITLE
Use font-size: 100% in _foundation.scss

### ISSUE THREAD

**Issue by matthias-vogt** [jaydenseric/Barebones#8]
Please consider using `font: 100%/1 $sans-serif;` instead of `font: 16px/1 $sans-serif;` in `_foundation.scss` for [accessibility reasons](http://terrillthompson.com/blog/589).

**Comment by jaydenseric** [comment]
Thanks for the suggestion. As the contents of `_foundation.scss` now live in a seperate repo ([Fix](https://github.com/jaydenseric/Fix)), I have actioned this change there too.
